### ISSUE TITLE
sanitizeProps still causes error

### ISSUE THREAD

**Issue by rmertens** [reactjs/react-modal#165]
### Summary:

The `Uncaught TypeError: Cannot delete property 'ref' of #<Object>` of issue #160 does not seem to have been solved completely. I encountered it again when using react-modal in combination with redux-form.

### Steps to reproduce:

I isolated the example here:
https://github.com/rmertens/react-modal-bug-example/tree/redux-form

1. npm install
2. ./node_modules/webpack/bin/webpack.js
3. open index.html, click open, and click the select

### Additional notes:
Using react 15.0.1

**Comment by diasbruno** [comment]
@rmertens thanks! i'll have a look on it.

**Comment by diasbruno** [comment]
Maybe we should just deprecate `sanitizeProps()`. Any thoughts?

> Most props on a JSX element are passed on to the component, however, there are two special props (**ref and key**) which are used by React, and are thus **not forwarded to the component**.
> 
> For instance, attempting to access this.props.key from a component (eg. the render function) is not defined. If you need to access the same value within the child component, you should pass it as a different prop (ex: <ListItemWrapper key={result.id} id={result.id} />) While this may seem redundant, it's important to separate app logic from reconciling hints.

https://gist.github.com/jimfb/fb2a04fe3fa4637d7d62

**Comment by wikiwong** [comment]
Forgive me if this is an ignorant question, but what is deleting the `ref` passed into the <Modal> intended to do?  Maybe this sanitization would save some memory, but if the <Modal> never references the ref property inside it's component logic, wouldn't it be benign to simply ignore it's existence?

**Comment by diasbruno** [comment]
Just trying to figure it out too. In a few tests, I didn't see it got defined in the Modal.js. I'll try to find a good reason to, maybe, deprecate it or find a correct fix.

**Comment by claydiffrient** [comment]
I think that back in previous versions of react, `renderSubtreeIntoContainer` needed the props to be removed or something like that or it would cause issues.  That being said, it could have just been an extra safety measure when first implemented.

In any case, if you can remove it completely and the tests still pass, I'm happy to merge it and just be done with `sanitizeProps`.

**Comment by diasbruno** [comment]
Awesome, @claydiffrient. Thanks for pointing this out! I'll check it out.

**Comment by wikiwong** [comment]
This didn't make it in to 1.2.0 ?

:(

**Comment by diasbruno** [comment]
@wikiwong Yesterday I spend sometime on this, kinda long debug session...without success :/
Tested with react `0.14.8, 15.0.0 and 15.0.1`. 
I got no problem running the modal without this function, but maybe I'm missing something.

**Comment by claydiffrient** [comment]
Worry @wikiwong, this didn't.  I just released a version with the latest changes that had been merged.  I didn't do any concrete work to make it happen.  If someone gets a PR in, I'll release another version with it as soon as I can. Otherwise, it might be a couple days until I can make and test the changes myself.

**Comment by wikiwong** [comment]
Thanks @diasbruno and @claydiffrient !  

I just upgraded my Redux and react-redux packages to the latest and the problem seems to have disappeared.  Specifically, I updated these two packages in my package.json:

```
"redux": "3.5.1",
"react-redux": "4.4.5"
```

@rmertens @diasbruno does that resolve the issue for you as well?

**Comment by rmertens** [comment]
@wikiwong it doesn't seem to resolve it for me [(example)](https://github.com/rmertens/react-modal-bug-example/tree/redux-form)
