### ISSUE TITLE
If 2 or more modals are open and one is closed, `ReactModal__Body--open` class is erroneously removed

### ISSUE THREAD

**Issue by ameyms** [reactjs/react-modal#231]
### Summary:

If two or more modals are open and one is closed, `ReactModal__Body--open` class is erroneously removed from body element
### Steps to reproduce:
1. Open a modal M1
2. Open a second modal M2
3. Close M2. The class `ReactModal__Body--open` will no longer exist on `body` element.
### Expected behavior:

The class `ReactModal__Body--open` should be active on the `body` element as long as there is at least _one_ instance of modal open
### Additional notes:

Perhaps we need to keep track of the total number of open modal instances?
https://github.com/reactjs/react-modal/blob/6550b87636546701e4aa9d90a67b4c2f431a86fe/lib/components/Modal.js#L66-L73

**Comment by thesbros** [comment]
I made a (bad) decorator to fix this, if it helps anyone: https://gist.github.com/thesbros/b9ff804902d5ecc53d92caf8e81dea9b

**Comment by fedeoo** [comment]
Even the [demo](https://reactcommunity.org/react-modal/) still has this bug!

**Comment by iluminus** [comment]
Hi,

When do you expect this bug to be resolved?
I have the same issue and am waiting for the resolution before I upgrade to the latest version.

Thanks!

**Comment by claydiffrient** [comment]
@iluminus I'm pretty sure this should be solved on the 1.7.x release.  Please give it a try and see if it works for you.  If it does, we'll close this issue.  I think it should be closed already, but I'll hold it open to get verification from you.

**Comment by iluminus** [comment]
@claydiffrient I checked and it works when installing your latest version.
Thank you!

**Comment by nickaversano** [comment]
I'm still experiencing this issue with multiple `ReactModal`s on the page. The `ReactModal__Body--open` gets added and then immediately removed on page reload. Inspecting the dom then shows one `ReactModalPortal` with children that `isOpen=true` for.
